[features]
seeds = false
skip-lint = false
[programs.localnet]
blockchain = "6iwFtczMvCR4s42UXSEF7KDmLhibbuFyuDCAwcABLVqu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/georgegichuru/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
